### ISSUE TITLE
All players lose points

### ISSUE THREAD

**Issue by Sachakir** [Dumuzy/KeizerForClubs#46]
Hello Demuzy,

Thank you for letting use this software, I could organise a little tournement with it.

I don't know if it is a bug or a normal behaviour. I have read the docs on the internet like this one : https://jbfsoftware.com/wordpress/sevilla-keizer/
but I couldn't find a answer.

The problem: Player that lose at the first round (They keep their starting amount of points, lets say a player Alex had 5 points at the beggining). After the second round, Alex didn't win and has his score decreased to 4. (I thought it should be keept at 5 points).

I understand that after you win the 1st round, after the second his points can be modified depending on the rank of the opponent in the first round. But I don't understant the rule for points where the player lose the first round.

Thank you in advance.

**Comment by Dumuzy** [comment]
Hello Sachakir, 
please attach the s3db file that is belonging to the mentioned behaviour and I will check it out.

**Comment by Sachakir** [comment]
Hello Dumuzy,

Here I have the file : Tournoi AVS nov 2023.s3db
It describes the tournement with 9 players. After 2 rounds.
This is the standing after 2nd round.

[image: image.png]
There were 8 players playing the first round and 4 players playing the
second round.
I removed the second round and here is the ranking after the first round.
[image: image.png]
Here we can see for example, Nathan lost both rounds, he had 7 points after
the first round and 5 points after the second.

For parameters I set all bonus to zero
[image: image.png]
Thank you your fast response ;)

**Comment by Sachakir** [comment]
I think I forgot to attach the file

**Comment by Dumuzy** [comment]
The attachments still seem not to be there.

**Comment by Sachakir** [comment]
[Tournoi AVS nov 2023.zip](https://github.com/Dumuzy/KeizerForClubs/files/13471862/Tournoi.AVS.nov.2023.zip)
Here is the zip with the s3db file.

For my last messages I replied by email, the files are attached to emails.

**Comment by Dumuzy** [comment]
I think several things came together here. 
1. A small bug in the software: Two of your players, Nathan and Damien do have the exact same rating. This is not handled correctly in the program. When sorting the player list before it is not defined which one of those two will be before the other one.   Not good and probably a part of the problem.  

2. @Sachakir: I suspect that you have changed the settings factor "Ratio du gain entre 1er et dernier" after the first round from 3 to 3.5.   The higher this factor, the lower the Keizer-points you get.    Is it true, did you change this factor after the first round?

4. When looking at the table of the first round after the second round, what you see is not a freshly calculated table, but the original table how it was shown to you after the first round. So a change of a factor in the settings won't be reflected in that first round table when you look at it after 2nd round.

**Comment by Sachakir** [comment]
2. I did not change this ratio. At the beginning of the tournement, I set
bonuses to 0. This factor was not change.

3. Ok, Can this factor be calculated automatically ? If a player enters
only in the second round and not the first ?

**Comment by Dumuzy** [comment]
I've looked into this again. 

The case is: 
Every player always gets added Keizer points **according to his rank before the round**. If he lost or won.  

Before the first round, this rank is calculated from rating. In your case, let's look at Anaelle. Before round 1, she was placed 2nd, as she had the 2nd best rating. With Keizer ratio of 3-to-1 and nine players, the first one in table gets 12 rank points and the second one (Anaelle) gets 11 rank points. So Anaelle got 11 rank points as Keizer points after the first round. She lost the first round and got nothing else.  Thus her 11 points after rnd 1. 

With these 11 points, after the first round, she was placed #4 and so she got 9 rank points as keizer points for round two. And 6 points because of her win in Round 2 = 15 Keizer points. If she had lost rnd 2, she had gotten these 9 rank points only. Less than the round before. It would seem she lost points. 

Similar things happened for Nathan, Romain and Sylvestre. Because they lost the first round, they got less rank points for the 2nd round. All of this seems correct to me as far as I understand the Keizer system. 

Not all players lose points.  Some others got more rank points in the 2nd round than in the first.  E.g. Laura, she got 5 rank points in rnd 1 and 6 points because of her victory. 
In the calculation for the 2nd round, she got 8 rank points and 5 points for her victory in rnd 1. So she had 2 Keizer points more than in round 1, even though her victory vs Romain counted less. 

This is not a bug.
